// src/app/features/cab/services/cab.service.ts



import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs'; // Using rxjs for asynchronous operations
export interface Driver {id: string;name: string;cabModel: string;licensePlate: string;status: 'available' | 'on-trip' | 'offline';}
@Injectable({
  providedIn: 'root',
})
export class CabService {
  private http = inject(HttpClient);
  private apiUrl = 'https://your-api-domain.com/api/drivers';
  private mockDrivers: Driver[] = [
    { id: '101', name: 'Ravi Sharma', cabModel: 'Sedan Z', licensePlate: 'UP16AB1234', status: 'available' },
    { id: '102', name: 'Priya Singh', cabModel: 'SUV X', licensePlate: 'DL05CD5678', status: 'on-trip' },
    { id: '103', name: 'Amit Verma', cabModel: 'Hatchback Y', licensePlate: 'HR26EF9012', status: 'offline' },
  ];
  getDrivers(): Observable<Driver[]> {
  //return this.http.get<Driver[]>(this.apiUrl); 
  return of(this.mockDrivers);
}

  /**
   * Retrieves a single driver by ID.
   * @param id The ID of the driver.
   */
  getDriver(id: string): Observable<Driver | undefined> {
    // 💡 Real API Call: return this.http.get<Driver>(`${this.apiUrl}/${id}`);
    
    // Using mock data for demonstration
    const driver = this.mockDrivers.find(d => d.id === id);
    return of(driver);
  }

  /**
   * Updates an existing driver's details.
   * @param driver The driver object with updated details.
   */
  updateDriver(driver: Driver): Observable<Driver> {
    // 💡 Real API Call: return this.http.put<Driver>(`${this.apiUrl}/${driver.id}`, driver);
    
    // Mock Update Logic (finding and replacing in the array)
    const index = this.mockDrivers.findIndex(d => d.id === driver.id);
    if (index > -1) {
      this.mockDrivers[index] = driver;
    }
    return of(driver);
  }

  /**
   * Creates a new driver entry.
   * @param newDriver The new driver object (ID might be generated by the backend).
   */
  createDriver(newDriver: Omit<Driver, 'id' | 'status'>): Observable<Driver> {
     // 💡 Real API Call: return this.http.post<Driver>(this.apiUrl, newDriver);
     
     // Mock Create Logic
     const newId = (this.mockDrivers.length + 101).toString();
     const driver: Driver = { 
        ...newDriver, 
        id: newId, 
        status: 'available' // Default status
     };
     this.mockDrivers.push(driver);
     return of(driver);
  }
}